### ISSUE TITLE
How to run this with Portainer

### ISSUE THREAD

**Issue by etnaaflonne123** [JoshuaTheMiller/Terraria#3]
i keep getting this issue and i cannot fix it can you help me out pls id like to get this running for friends if it works and all.

if it says in the text im missing it im brand new to this game infact i have never played. so im unsure how to work this.

im running OMG 5 with docker (portainer)  16 gigs of ram quad core  no beefy but it runs minecraft plex 2 dst servers and netdata + openvpn with out even using 30%so should be able to handle this 

[id love a direct reply via discord if u got one and if u do more dockers id like to pick some up specially ffxi i want that one bad XD ]]
![issue (FILEminimizer)](https://user-images.githubusercontent.com/46465728/96743235-a0389c80-1378-11eb-9850-0f376b622e75.jpg)

**Comment by JoshuaTheMiller** [comment]
Hey @etnaaflonne123! I don't normally run portainer, but I've been meaning to give it a try and this gives me a good excuse! 

I'm fairly busy the rest of the week, but I should be able to find some time to dig into why this isn't working by Sunday. It seems to have something to do with the startup being interactive 🤔 

Are you able to [pass commands to the container](https://codeopolis.com/posts/beginners-guide-to-portainer/#Advanced_Container_Settings) when you start it? If so, passing the values present in the [Quickstart](https://github.com/JoshuaTheMiller/Terraria#quickstart) _should_ allow the container to instantiate successfully.

**Comment by JoshuaTheMiller** [comment]
About Discord, I set up this server with a `dockerfiles` text channel: https://discord.gg/qUjmy7K

**Comment by JoshuaTheMiller** [comment]
Closed as the issue had to do with commands not being passed. The dockerfile has since been updated to have better defaults 👍
